apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baris1892/datascientest-final-project.git
    targetRevision: develop
    path: infrastructure/charts/frontend
    helm:
      releaseName: frontend
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
