apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: certificate@baris.cloud-ip.cc
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: traefik

# Let's Encrypt staging environment is used due to rate limits
# debug with: kubectl describe clusterissuer letsencrypt-staging
